# Site
name: 'Amit Singh Blog'
description: 'Blog of Amit'
logo: 'assets/images/1.jpg'
favicon: 'assets/images/favicon.png'
baseurl: ""
disqus: 'amitsinghblog'
email: 'amit1093@gmail.com'
mailchimp-list: 'https://productstories.substack.com/'

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    amit:
      name:           Amit Singh
      site:           https://www.amitsingh.blog
      avatar:         assets/images/profile.png
      bio:            "Hi, I am Amit. Currently building Memer - a memesharing app. Ex-Kae Capital. IIT Bombay alumnus"
      email:          amit1093@gmail.com
      twitter:        https://twitter.com/iamitsy

  
 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: sal
      avatar: /assets/images/avatar1.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]